version: '3'
services:
    web:
        build: .
        env_file:
            - .env
        ports:
            - "8000:8000"
        volumes: 
            - .:/app
        depends_on: 
            - postgres
    postgres:
        image: postgres:13.2
        env_file:
            - .env
        expose: 
            - "5432"