# Generated by Django 3.2 on 2021-05-01 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('idCalificacion', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('puntaje', models.PositiveSmallIntegerField(default=1)),
                ('descripcion', models.CharField(max_length=30)),
                ('resultado', models.CharField(blank=True, choices=[('a', 'Aceptado'), ('r', 'Rechazado')], default='a', help_text='Resultado de la calificación', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('codDesafio', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=70)),
                ('resolusion', models.CharField(max_length=70)),
                ('lenguajeProgramacion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('codDocumento', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=15)),
                ('peso', models.CharField(max_length=5)),
                ('documento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('codPostulante', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
                ('fechanamiento', models.DateField()),
                ('nivelEscolar', models.CharField(choices=[('P', 'Profesional'), ('T', 'Técnico'), ('E', 'Estudiante Universitario'), ('M', 'Magister'), ('D', 'Doctorado')], default='E', max_length=1)),
                ('genero', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='F', max_length=1)),
                ('rut', models.CharField(max_length=15)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoUniApp.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PostulanteDesafio',
            fields=[
                ('codPostulanteDesafio', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('resolucionPostulante', models.CharField(max_length=70)),
                ('tiemporespuesta', models.TimeField()),
                ('estado', models.BooleanField(default=True)),
                ('desafio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoUniApp.desafio')),
                ('postulante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoUniApp.postulante')),
            ],
        ),
        migrations.CreateModel(
            name='Entrevista',
            fields=[
                ('codEntrevista', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nota', models.PositiveSmallIntegerField(default=1)),
                ('tiempo', models.TimeField()),
                ('calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoUniApp.calificacion')),
                ('entrevistador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoUniApp.usuario')),
                ('postulante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoUniApp.postulante')),
                ('postulantedesafio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DjangoUniApp.postulantedesafio')),
            ],
        ),
    ]
