# Generated by Django 3.2 on 2021-05-01 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoUniApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulante',
            name='documento',
        ),
    ]
